name: 'Upload a Release'
description: 'Upload a release which will deployed to your project.'
author: 'Serve My Site'

branding:
  icon: 'upload'
  color: 'blue'

inputs:
  session-reference:
    description: 'The identifier used to obtain a session to your project.'
    required: true
  project-reference:
    description: 'The unique identifier for the project where you would like this release uploaded. You can find this by navigating to your project at https://servemy.site.'
    required: true
  path:
    description: 'A file, directory or wildcard pattern that describes what to upload.'
    required: true
  activate:
    description: 'A flag indicating if the release should be activated once it has been created.'
    required: false

outputs:
  release-reference:
    description: 'A unique identifier for the release that was just uploaded. Empty if the artifact upload failed.'

runs:
  using: node20
  main: dist/index.js
